# Goal
int32 order
bool request_open_gripper
bool request_close_gripper
bool request_greeting
bool move_robot
bool check_robot_status
---
# Result
int32[] sequence
string greeting_message
int32 goal_id
---
# Feedback
int32[] partial_sequence
int32 current_count
bool robot_moving
